src/VasutInfo/src/action/AddWagonActionBean.java
package action;

import java.util.List;

import dao.VasutInfoDAO;

import model.Train;
import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.RedirectResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.action.SimpleMessage;

public class AddWagonActionBean extends BaseActionBean{
	private static final String VIEW = "/WEB-INF/jsp/addwagon.jsp";
	
	private boolean bicycle;
	private boolean smoking;
	private boolean buffetCar;
	private int classNumber;
	private int trainID;

	public String[] getEnums() {
        String[] s = {"yes","no"};
        return s;
    }
	
	public int[] getClasses() {
        int[] i = {1,2};
        return i;
    }

	@DefaultHandler
    public Resolution view() {
        return new ForwardResolution(VIEW);
    }
	
	public Resolution addWagon(){
		VasutInfoDAO dao = new VasutInfoDAO();
		dao.addWagon(bicycle, smoking, buffetCar, classNumber, trainID);
		getContext().getMessages().add(new SimpleMessage("Added a wagon to {0} train." , dao.getTrain(trainID).getName()));
		return new RedirectResolution(getClass());
	}
	
	public List<Train> getTrains(){
		VasutInfoDAO dao = new VasutInfoDAO();
		return dao.getTrains();
	}
	
	
	public boolean isBicycle() {
		return bicycle;
	}


	public void setBicycle(boolean bicycle) {
		this.bicycle = bicycle;
	}


	public boolean isSmoking() {
		return smoking;
	}


	public void setSmoking(boolean smoking) {
		this.smoking = smoking;
	}


	public boolean isBuffetCar() {
		return buffetCar;
	}


	public void setBuffetCar(boolean buffetCar) {
		this.buffetCar = buffetCar;
	}


	public int getClassNumber() {
		return classNumber;
	}


	public void setClassNumber(int classNumber) {
		this.classNumber = classNumber;
	}


	public int getTrainID() {
		return trainID;
	}


	public void setTrainID(int trainID) {
		this.trainID = trainID;
	}
}

src/VasutInfo/src/action/ListDiscountActionBean.java
package action;
import java.util.List;
import dao.VasutInfoDAO;
import model.Discount;
import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;

public class ListDiscountActionBean extends BaseActionBean {

	private static final String VIEW = "/WEB-INF/jsp/listdiscount.jsp";
	
	@DefaultHandler
    public Resolution view() {
        return new ForwardResolution(VIEW);
    }
	
	public List<Discount> getDiscounts(){
		VasutInfoDAO dao = new VasutInfoDAO();
		return dao.getDiscounts();
	}

}

src/VasutInfo/src/action/ListTrainActionBean.java
package action;

import java.util.List;

import dao.VasutInfoDAO;
import model.Train;
import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;

public class ListTrainActionBean extends BaseActionBean{
	private static final String VIEW = "/WEB-INF/jsp/listtrain.jsp";
	
	@DefaultHandler
    public Resolution view() {
        return new ForwardResolution(VIEW);
    }
	
	
	public List<Train> getList(){
		VasutInfoDAO dao = new VasutInfoDAO();
		return dao.getTrains();
	}
}

src/VasutInfo/WebContent/WEB-INF/jsp/adddiscount.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
  title="Add Discount">
  <s:layout-component name="body">
  	<s:errors/>
    <p>Add a new discount</p>
    <s:form beanclass="action.AddDiscountActionBean">
		<table>
		        <tr>
		          <td>Discount name:</td>
		          <td><s:text name="discountName"/></td>
		        </tr>
		        <tr>
		          <td>Discount percentage:</td>
		          <td><s:text name="percentage"/></td>
		        </tr>
      		</table>
      <s:submit name="addDiscount" value="Add Discount"/>
    </s:form>
  </s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/addtrain.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
  title="Add Train">
  <s:layout-component name="body">
  	<s:messages/>
  	<s:errors/>
    <p>Push the button below to add a new train.</p>
    <s:form beanclass="action.AddTrainActionBean">
      <table>
        <tr>
          <td>Train name:</td>
          <td><s:text name="trainName"/></td>
        </tr>
      </table>
      <s:submit name="addTrain" value="Add Train"/>
    </s:form>
  </s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/addwagon.jsp
<%@page contentType="text/html;charset=ISO-8859-1" language="java"%>
<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
	title="Add Wagon">
	<s:layout-component name="body">
		<s:messages/>
		<s:form beanclass="action.AddWagonActionBean">
			<table>
        		<tr>
         			<td>Train name:</td>
          			<td><s:select name="trainID">
						<s:option value="">Select a train...</s:option>
						<s:options-collection collection="${actionBean.trains}" value="ID" label="name"/>
						</s:select>
					</td>
        		</tr>
        		<tr>
         			<td>Bicycle:</td>
          			<td><c:forEach var="bicycle" items="${actionBean.enums}">
              				<s:radio name="bicycle" value="${bicycle}"/>${bicycle}
            			</c:forEach>
            		</td>
        		</tr>
        		<tr>
         			<td>Smoking:</td>
          			<td><c:forEach var="smoking" items="${actionBean.enums}">
              				<s:radio name="smoking" value="${smoking}"/>${smoking}
            			</c:forEach>
            		</td>
        		</tr>
        		<tr>
         			<td>Buffet Car:</td>
          			<td><c:forEach var="buffetCar" items="${actionBean.enums}">
              				<s:radio name="buffetCar" value="${buffetCar}"/>${buffetCar}
            			</c:forEach>
            		</td>
        		</tr>
        		<tr>
         			<td>Class number:</td>
          			<td><c:forEach var="classNumber" items="${actionBean.classes}">
              				<s:radio name="classNumber" value="${classNumber}"/>${classNumber}
            			</c:forEach>
            		</td>
        		</tr>
      		</table>
      		
      		<s:submit name="addWagon" value="Add Wagon"/>
		</s:form>
	</s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/deletediscount.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
  title="Delete Discount">
  <s:layout-component name="body">
  	<s:errors/>
    <p>Select a discount to delete.</p>
    <s:form beanclass="action.DeleteDiscountActionBean">
		<div><s:select name="selectedDiscount">
			<s:option value="">Select a discount...</s:option>
			<s:options-collection collection="${actionBean.discounts}" value="ID" label="name"/>
		</s:select></div>
      <s:submit name="deleteDiscount" value="Delete Discount"/>
    </s:form>
  </s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/deletetrain.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
  title="Delete Train">
  <s:layout-component name="body">
  	<s:errors/>
  	<s:messages/>
    <p>Select a train to delete.</p>
    <s:form beanclass="action.DeleteTrainActionBean">
		<div><s:select name="selectedTrain">
			<s:option value="">Select a train...</s:option>
			<s:options-collection collection="${actionBean.trains}" value="ID" label="name"/>
		</s:select></div>
      <s:submit name="deleteTrain" value="Delete Train" />
    </s:form>
  </s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/listdiscount.jsp
<%@page contentType="text/html;charset=ISO-8859-1" language="java"%>

<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
	title="List of Discounts">
	<s:layout-component name="body">
		<s:form beanclass="action.ListDiscountActionBean">
			<d:table name="${actionBean.discounts}" id="station" requestURI="" defaultsort="1"
					 defaultorder="ascending">
				<d:column title="Discount id" property="ID" sortable="true" />
				<d:column title="Discount name" property="name" sortable="true" />
				<d:column title="Discount percentage" property="percentage" sortable="true" />
			</d:table>
		</s:form>
	</s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/liststation.jsp
<%@page contentType="text/html;charset=ISO-8859-1" language="java"%>

<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
	title="List of Stations">
	<s:layout-component name="body">
		<s:form beanclass="action.ListStationActionBean">
			<d:table name="${actionBean.list}" id="station" requestURI="" defaultsort="1"
					 defaultorder="ascending">
				<d:column title="Station id" property="ID" sortable="true" />
				<d:column title="Station name" property="name" sortable="true" />
			</d:table>
		</s:form>
	</s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/listwagon.jsp
<%@page contentType="text/html;charset=ISO-8859-1" language="java"%>

<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
	title="Wagon List">
	<s:layout-component name="body">
		<s:form beanclass="action.ListWagonActionBean">
			<d:table name="${actionBean.list}" id="wagon" requestURI="" defaultsort="1"
					 defaultorder="descending">
				<d:column title="Wagon id" property="ID" sortable="true" />
				<d:column title="Bicycle" property="bicycle"/>
				<d:column title="Smoking" property="smoking"/>
				<d:column title="Buffet Car" property="buffetCar"/>
				<d:column title="Class number" property="classNumber"/>
				<d:column title="TrainID" property="trainID" sortable="true"/>
			</d:table>
		</s:form>
	</s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/register.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/layout_general.jsp"
  title="Registration">
  <s:layout-component name="body">
  	<s:errors/>
    <p>Register to create an account:</p>
    <s:form beanclass="action.RegisterActionBean">
      <table>
        <tr>
          <td>Name:</td>
          <td><s:text name="name"/></td>
        </tr>
        <tr>
          <td>User name:</td>
          <td><s:text name="username"/></td>
        </tr>
        <tr>
          <td>Password:</td>
          <td><s:password name="password"/></td>
        </tr>
        <tr>
          <td>Confirm Password:</td>
          <td><s:password name="confirmPassword"/></td>
        </tr>
        <tr>
          <td></td>
          <td>
            <s:submit name="register" value="Register"/>
            <s:submit name="cancel" value="Cancel"/>
          </td>
        </tr>
      </table>
    </s:form>
  </s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/searchline_admin.jsp
<%@page contentType="text/html;charset=ISO-8859-1" language="java"%>

<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp" title="Search Lines">
	<s:layout-component name="body">
		<s:form beanclass="action.SearchLineAcionBean">
			<table>
		        <tr>
		          <td>Start:</td>
		          <td><s:text name="start"/></td>
		        </tr>
		        <tr>
		          <td>Stop:</td>
		          <td><s:text name="stop"/></td>
		        </tr>
      		</table>
      		<s:submit name="search" value="Search"/>
		</s:form>
	</s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/startuser.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	YEAH!!!
</body>
</html>

src/VasutInfo/WebContent/WEB-INF/jsp/updatestation.jsp
<%@page contentType="text/html;charset=ISO-8859-1" language="java"%>

<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
	title="Update a Station">
	<s:layout-component name="body">
		<s:form beanclass="action.UpdateStationActionBean">
			<table>
		        <tr>
		          <td>Station name:</td>
		          <s:select name="selectedID">
							<s:option value="">Select a station</s:option>
							<s:options-collection collection="${actionBean.list}" value="ID" label="name"/>
						</s:select>
		        </tr>
		        <tr>
		          <td>New name:</td>
		          <td><s:text name="newName"/></td>
		        </tr>
		        
      		</table>
      		<s:submit name="updateStation" value="Update Station"/>
		</s:form>
	</s:layout-component>
</s:layout-render>

src/VasutInfo/WebContent/WEB-INF/jsp/updatetrain.jsp
<%@page contentType="text/html;charset=ISO-8859-1" language="java"%>

<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_main.jsp"
	title="Update a Train">
	<s:layout-component name="body">
		<s:errors/>
		<s:messages/>
		<s:form beanclass="action.UpdateTrainActionBean">
			<table>
		        <tr>
		          <td>Train name:</td>
		          <td><s:select name="selectedID">
							<s:option value="">Select a train</s:option>
							<s:options-collection collection="${actionBean.list}" value="ID" label="name"/>
						</s:select>
				  </td>
		        </tr>
		        <tr>
		          <td>New name:</td>
		          <td><s:text name="newName"/></td>
		        </tr>
		        
      		</table>
      		<s:submit name="updateTrain" value="Update Train"/>
		</s:form>
	</s:layout-component>
</s:layout-render>